// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace BlazorApp_1.DataContext.Models
{
    public partial class sp_Employees_CursorResult
    {
        public string FName { get; set; }
        public string LName { get; set; }
        public string PhotoPath { get; set; }
    }
}
